# Site settings
title: A blog about engge game engine
email: scemino74@gmail.com
logo: /assets/img/logo.png
show_downloads: true
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: engge_the_game
github_username:  scemino
excerpt_separator: "<!--more-->"
show_excerpts: true

# Build settings
theme: minima

# Disqus Comments
disqus:
    # Leave shortname blank to disable comments site-wide.
    # Disable comments for any post by adding `comments: false` to that post's YAML Front Matter.
    shortname: engge
